(deftheme wombat
  "Created 2012-09-23.")

(custom-theme-set-variables
 'wombat
 '(ansi-color-names-vector ["#242424" "#e5786d" "#95e454" "#cae682" "#8ac6f2" "#333366" "#ccaa8f" "#f6f3e8"]))

(custom-theme-set-faces
 'wombat
 '(cursor ((t (:background "white"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#303030"))))
 '(highlight ((t (:background "#454545" :foreground "#ffffff" :underline t))))
 '(region ((t (:background "white" :foreground "black"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#333366" :foreground "#f6f3e8"))))
 '(isearch ((t (:background "green" :foreground "black"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#384048" :foreground "#a0a8b0"))))
 '(mode-line ((t (:background "green1" :foreground "black"))))
 '(mode-line-inactive ((t (:background "black" :foreground "chartreuse"))))
 '(minibuffer-prompt ((t (:foreground "green"))))
 '(escape-glyph ((t (:foreground "#ddaa6f" :weight bold))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(font-lock-keyword-face ((t (:foreground "DeepSkyBlue1"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#92a65e" :weight bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(link ((t (:foreground "lawn green" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline t))))
 '(button ((t (:background "green" :foreground "black"))))
 '(header-line ((((class color) (min-colors 89)) (:background "#303030" :foreground "#e7f6da"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-news-1-low ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-2-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-news-3-low ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#99968b"))))
 '(gnus-group-news-4-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-5-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-mail-1-low ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-mail-2-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-mail-3-low ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#e5786d" :weight bold))))
 '(default ((t (:background "black" :foreground "green")))))

(provide-theme 'wombat)
